baseurl = "https://eng618.github.io"           # The base URL of your Hugo site
title = "Eric Garcia"     # The title of your Hugo site
author = "Eric Garcia"   # The author name
googleAnalytics = ""    # Your Google Analytics tracking ID
enableRobotsTXT = true
language = "en-US"
paginate = 7            # The numbers of posts per page
theme = "hugo-terressa-theme"

[params]
    description = "This is my personal dev portfolio created with Hugo."
    favicon = "/favicon.ico"     # Relative URL for your favicon
    logo = ""        # Absolute URL for your logo

[params.hero]
    textColor = "" # Empty for default color

[params.copy] # Copyright
    copy = "© 2021 Garcia Enterprise" # Empty for default content

[params.social]
    twitter = "https://twitter.com/garciaericn"
    github = "https://github.com/ENG618"
    linkedin = "https://www.linkedin.com/in/garciaericn"
