# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: "Runs the project in development mode"
    cmds:
      - task: dev

  build:
    desc: "Builds the project for production"
    cmds:
      - bun run build

  dev:
    desc: "Starts the development server"
    cmds:
      - bun run dev

  format:
    desc: "Formats code with Prettier"
    cmds:
      - bun run format

  format:ci:
    desc: "Checks code formatting with Prettier (CI)"
    cmds:
      - bun run format:ci

  lint:
    desc: "Lints the code with ESLint"
    cmds:
      - bun run lint

  lint:fix:
    desc: "Fixes linting issues"
    cmds:
      - bun run lint:fix

  lint:report:
    desc: "Generates an HTML linting report"
    cmds:
      - bun run lint:report

  start:
    desc: "Starts the production server"
    cmds:
      - bun run start

  test:
    desc: "Runs tests with Vitest"
    cmds:
      - bun run test

  test:watch:
    desc: "Runs tests in watch mode"
    cmds:
      - bun run test:watch
