# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: "Runs the project in development mode"
    cmds:
      - task: dev

  build:
    desc: "Builds the project for production"
    cmds:
      - yarn build

  dev:
    desc: "Starts the development server"
    cmds:
      - yarn dev

  format:
    desc: "Formats code with Prettier"
    cmds:
      - yarn format

  format:ci:
    desc: "Checks code formatting with Prettier (CI)"
    cmds:
      - yarn format:ci

  lint:
    desc: "Lints the code with ESLint"
    cmds:
      - yarn lint

  lint:fix:
    desc: "Fixes linting issues"
    cmds:
      - yarn lint:fix

  lint:report:
    desc: "Generates an HTML linting report"
    cmds:
      - yarn lint:report

  prepare:
    desc: "Prepares the project (Husky setup)"
    cmds:
      - yarn prepare

  start:
    desc: "Starts the production server"
    cmds:
      - yarn start

  test:
    desc: "Runs tests with Vitest"
    cmds:
      - yarn test

  test:watch:
    desc: "Runs tests in watch mode"
    cmds:
      - yarn test:watch
