description = "This is my personal dev portfolio created with Hugo."
favicon = "/favicon.ico"
logo = "/images/profile_new.png"  # Replace with logo

[hero]
  textColor = "" # Empty for default color

[copy] # Copyright
  copy = "© 2021 Garcia Enterprise"

[social]
  twitter = "https://twitter.com/garciaericn"
  github = "https://github.com/ENG618"
  linkedin = "https://www.linkedin.com/in/garciaericn"

[form] # Contact form
    netlify = true
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[posts]
    showAuthor = false
    showDate = true
    showTags = true
    dateFormat = "Jan 2, 2006"
